<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ip-172-31-16-168" ignored="0" name="Default test" tests="3" failures="0" timestamp="2022-03-12T15:56:40 UTC" time="0.092" errors="0">
  <testcase name="@BeforeTest DataSetUP" time="0.008" classname="testclasses.BaseClass">
    <failure type="java.io.FileNotFoundException" message="exceldata.xlsx (No such file or directory)">
      <![CDATA[java.io.FileNotFoundException: exceldata.xlsx (No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.<init>(FileInputStream.java:138)
at java.io.FileInputStream.<init>(FileInputStream.java:93)
at testclasses.BaseClass.DataSetUP(BaseClass.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:645)
at org.testng.TestRunner.beforeRun(TestRunner.java:634)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest DataSetUP -->
  <testcase name="@BeforeMethod SetUp" time="0.0" classname="testclasses.BaseClass">
    <skipped/>
  </testcase> <!-- @BeforeMethod SetUp -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="testclasses.BaseClass">
    <skipped/>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="@BeforeMethod SetUp" time="0.0" classname="testclasses.BaseClass">
    <skipped/>
  </testcase> <!-- @BeforeMethod SetUp -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="testclasses.BaseClass">
    <skipped/>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="@BeforeMethod SetUp" time="0.0" classname="testclasses.BaseClass">
    <skipped/>
  </testcase> <!-- @BeforeMethod SetUp -->
  <testcase name="@AfterMethod TearDown" time="0.0" classname="testclasses.BaseClass">
    <skipped/>
  </testcase> <!-- @AfterMethod TearDown -->
  <testcase name="@AfterTest DataTearDown" time="0.0" classname="testclasses.BaseClass">
    <skipped/>
  </testcase> <!-- @AfterTest DataTearDown -->
  <testcase name="ExternalDataTest" time="0.0" classname="testclasses.LoginTest">
    <skipped/>
  </testcase> <!-- ExternalDataTest -->
  <testcase name="LoginFailureTest" time="0.0" classname="testclasses.LoginTest">
    <skipped/>
  </testcase> <!-- LoginFailureTest -->
  <testcase name="LoginSuccessTest" time="0.0" classname="testclasses.LoginTest">
    <skipped/>
  </testcase> <!-- LoginSuccessTest -->
</testsuite> <!-- Default test -->
